In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [6]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [77]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [11]:
model = Sequential()

In [16]:
model.add(Dense(32,activation = 'relu',input_dim = 8))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.fit(X_train,y_train,epochs = 100,batch_size = 32,validation_data=(X_test,y_test))

Epoch 1/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.6424 - loss: 0.6887 - val_accuracy: 0.6771 - val_loss: 0.6800
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.6795 - val_accuracy: 0.6771 - val_loss: 0.6701
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6424 - loss: 0.6725 - val_accuracy: 0.6771 - val_loss: 0.6603
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6424 - loss: 0.6656 - val_accuracy: 0.6771 - val_loss: 0.6517
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6424 - loss: 0.6608 - val_accuracy: 0.6771 - val_loss: 0.6439
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6424 - loss: 0.6562 - val_accuracy: 0.6771 - val_loss: 0.6402
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6424 - loss: 0.6543 - val_accuracy: 0.6771 - val_loss: 0.6350
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6424 - loss: 0.6520 - val_accuracy: 0.6771 - val_loss: 0.6335
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6424 - loss: 0.6514 - val_accuracy: 0.6771 - val_loss: 0.6316
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6424 - loss: 0.6505 - val_accuracy: 0.6771 - val_loss: 0.6306
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6424 - loss: 0.6497 - val_accuracy: 0.6771 - val_loss: 0.6290
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6424 - loss: 0.6484 - val_accuracy: 0.6771 - val_loss: 0.6269
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6424 - loss: 0.6467 - val_accuracy: 0.6771 - val_loss: 0.6241
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6424 - loss: 0.6444 - val_accuracy: 0.6771 - val_loss: 0.6208
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6424 - loss: 0.6416 - val_accuracy: 0.6771 - val_loss: 0.6174
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6424 - loss: 0.6388 - val_accuracy: 0.6771 - val_loss: 0.6133
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6355 - val_accuracy: 0.6771 - val_loss: 0.6104
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6424 - loss: 0.6322 - val_accuracy: 0.6771 - val_loss: 0.6062
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.6288 - val_accuracy: 0.6771 - val_loss: 0.6026
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6253 - val_accuracy: 0.6771 - val_loss: 0.5992
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6220 - val_accuracy: 0.6771 - val_loss: 0.5949
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6182 - val_accuracy: 0.6771 - val_loss: 0.5913
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6145 - val_accuracy: 0.6771 - val_loss: 0.5875
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6103 - val_accuracy: 0.6771 - val_loss: 0.5843
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.6063 - val_accuracy: 0.6771 - val_loss: 0.5808
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.6022 - val_accuracy: 0.6771 - val_loss: 0.5767
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5976 - val_accuracy: 0.6771 - val_loss: 0.5727
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5931 - val_accuracy: 0.6771 - val_loss: 0.5687
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5882 - val_accuracy: 0.6771 - val_loss: 0.5643
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5832 - val_accuracy: 0.6771 - val_loss: 0.5600
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5780 - val_accuracy: 0.6771 - val_loss: 0.5559
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5725 - val_accuracy: 0.6771 - val_loss: 0.5519
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5668 - val_accuracy: 0.6771 - val_loss: 0.5480
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6424 - loss: 0.5615 - val_accuracy: 0.6771 - val_loss: 0.5436
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5552 - val_accuracy: 0.6771 - val_loss: 0.5396
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5493 - val_accuracy: 0.6771 - val_loss: 0.5358
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6424 - loss: 0.5435 - val_accuracy: 0.6771 - val_loss: 0.5325
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5374 - val_accuracy: 0.6771 - val_loss: 0.5285
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5313 - val_accuracy: 0.6771 - val_loss: 0.5255
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5257 - val_accuracy: 0.6771 - val_loss: 0.5229
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5192 - val_accuracy: 0.6771 - val_loss: 0.5214
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.5139 - val_accuracy: 0.6771 - val_loss: 0.5184
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5085 - val_accuracy: 0.7656 - val_loss: 0.5180
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7882 - loss: 0.5023 - val_accuracy: 0.7604 - val_loss: 0.5172
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4972 - val_accuracy: 0.7604 - val_loss: 0.5168
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7917 - loss: 0.4926 - val_accuracy: 0.7552 - val_loss: 0.5167
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4890 - val_accuracy: 0.7552 - val_loss: 0.5169
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4848 - val_accuracy: 0.7552 - val_loss: 0.5181
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7882 - loss: 0.4814 - val_accuracy: 0.7552 - val_loss: 0.5186
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4776 - val_accuracy: 0.7500 - val_loss: 0.5190
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8038 - loss: 0.4745 - val_accuracy: 0.7448 - val_loss: 0.5196
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4725 - val_accuracy: 0.7448 - val_loss: 0.5196
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.4699 - val_accuracy: 0.7552 - val_loss: 0.5212
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4672 - val_accuracy: 0.7552 - val_loss: 0.5211
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4652 - val_accuracy: 0.7448 - val_loss: 0.5219
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8177 - loss: 0.4632 - val_accuracy: 0.7448 - val_loss: 0.5217
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8142 - loss: 0.4618 - val_accuracy: 0.7448 - val_loss: 0.5214
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4596 - val_accuracy: 0.7448 - val_loss: 0.5220
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.4582 - val_accuracy: 0.7396 - val_loss: 0.5222
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4568 - val_accuracy: 0.7448 - val_loss: 0.5225
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.4544 - val_accuracy: 0.7396 - val_loss: 0.5223
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8212 - loss: 0.4529 - val_accuracy: 0.7448 - val_loss: 0.5207
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.4515 - val_accuracy: 0.7448 - val_loss: 0.5204
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.4500 - val_accuracy: 0.7500 - val_loss: 0.5213
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8177 - loss: 0.4484 - val_accuracy: 0.7448 - val_loss: 0.5218
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.4469 - val_accuracy: 0.7448 - val_loss: 0.5223
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.4451 - val_accuracy: 0.7448 - val_loss: 0.5227
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8229 - loss: 0.4443 - val_accuracy: 0.7396 - val_loss: 0.5220
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.4423 - val_accuracy: 0.7344 - val_loss: 0.5204
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.4412 - val_accuracy: 0.7448 - val_loss: 0.5218
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.4397 - val_accuracy: 0.7448 - val_loss: 0.5206
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8316 - loss: 0.4384 - val_accuracy: 0.7396 - val_loss: 0.5202
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.4371 - val_accuracy: 0.7396 - val_loss: 0.5215
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.4364 - val_accuracy: 0.7448 - val_loss: 0.5213
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.4348 - val_accuracy: 0.7448 - val_loss: 0.5234
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8299 - loss: 0.4340 - val_accuracy: 0.7448 - val_loss: 0.5201
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8316 - loss: 0.4312 - val_accuracy: 0.7396 - val_loss: 0.5216
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4300 - val_accuracy: 0.7448 - val_loss: 0.5207
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8299 - loss: 0.4287 - val_accuracy: 0.7448 - val_loss: 0.5222
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.4276 - val_accuracy: 0.7396 - val_loss: 0.5240
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.4262 - val_accuracy: 0.7448 - val_loss: 0.5238
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8368 - loss: 0.4252 - val_accuracy: 0.7396 - val_loss: 0.5202
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - loss: 0.4223 - val_accuracy: 0.7448 - val_loss: 0.5209
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8351 - loss: 0.4204 - val_accuracy: 0.7448 - val_loss: 0.5221
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8316 - loss: 0.4198 - val_accuracy: 0.7448 - val_loss: 0.5224
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8368 - loss: 0.4170 - val_accuracy: 0.7396 - val_loss: 0.5226
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8385 - loss: 0.4158 - val_accuracy: 0.7448 - val_loss: 0.5218
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8368 - loss: 0.4144 - val_accuracy: 0.7448 - val_loss: 0.5245
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8385 - loss: 0.4126 - val_accuracy: 0.7448 - val_loss: 0.5243
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8420 - loss: 0.4104 - val_accuracy: 0.7396 - val_loss: 0.5255
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8368 - loss: 0.4100 - val_accuracy: 0.7448 - val_loss: 0.5245
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8420 - loss: 0.4078 - val_accuracy: 0.7396 - val_loss: 0.5268
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8403 - loss: 0.4057 - val_accuracy: 0.7448 - val_loss: 0.5270
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.4052 - val_accuracy: 0.7500 - val_loss: 0.5285
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8420 - loss: 0.4052 - val_accuracy: 0.7396 - val_loss: 0.5319
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.4031 - val_accuracy: 0.7552 - val_loss: 0.5305
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8472 - loss: 0.4019 - val_accuracy: 0.7500 - val_loss: 0.5337
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8455 - loss: 0.3995 - val_accuracy: 0.7500 - val_loss: 0.5320
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8455 - loss: 0.3981 - val_accuracy: 0.7448 - val_loss: 0.5352
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3982 - val_accuracy: 0.7552 - val_loss: 0.5346

## How to Select Appropriate Optimizer

In [19]:
%pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 6.1 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [20]:
import keras_tuner as kt

In [21]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation = 'relu',input_dim = 8))
  model.add(Dense(1,activation= 'sigmoid'))
  optmizer = hp.Choice('optimizer',values = ["adam",'sgd','rmsprop','adadelta'])
  model.compile(optimizer = optmizer, loss = 'binary_crossentropy',metrics = ['accuracy'])
  return model

In [23]:
tuner = kt.RandomSearch(build_model,objective = 'val_accuracy',max_trials = 5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.59375

Best val_accuracy So Far: 0.7708333134651184
Total elapsed time: 00h 00m 12s

In [25]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [27]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [28]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.fit(X_train,y_train,epochs = 100,initial_epoch = 5,validation_data = (X_test,y_test),batch_size = 32)

Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7517 - loss: 0.5404 - val_accuracy: 0.7760 - val_loss: 0.5226
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7535 - loss: 0.5227 - val_accuracy: 0.7812 - val_loss: 0.5090
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7552 - loss: 0.5115 - val_accuracy: 0.7812 - val_loss: 0.4977
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7604 - loss: 0.5022 - val_accuracy: 0.7865 - val_loss: 0.4881
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7604 - loss: 0.4945 - val_accuracy: 0.7865 - val_loss: 0.4804
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7587 - loss: 0.4887 - val_accuracy: 0.7917 - val_loss: 0.4744
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7604 - loss: 0.4841 - val_accuracy: 0.7865 - val_loss: 0.4695
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4798 - val_accuracy: 0.7865 - val_loss: 0.4658
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4766 - val_accuracy: 0.7865 - val_loss: 0.4627
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4737 - val_accuracy: 0.7865 - val_loss: 0.4597
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7656 - loss: 0.4710 - val_accuracy: 0.7917 - val_loss: 0.4577
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.4688 - val_accuracy: 0.7969 - val_loss: 0.4553
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7691 - loss: 0.4669 - val_accuracy: 0.8021 - val_loss: 0.4542
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7708 - loss: 0.4652 - val_accuracy: 0.8021 - val_loss: 0.4531
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4635 - val_accuracy: 0.7969 - val_loss: 0.4523
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4624 - val_accuracy: 0.7969 - val_loss: 0.4514
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7743 - loss: 0.4610 - val_accuracy: 0.7969 - val_loss: 0.4510
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4594 - val_accuracy: 0.8021 - val_loss: 0.4508
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7795 - loss: 0.4585 - val_accuracy: 0.8073 - val_loss: 0.4506
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4569 - val_accuracy: 0.8073 - val_loss: 0.4503
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7743 - loss: 0.4558 - val_accuracy: 0.8021 - val_loss: 0.4499
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7795 - loss: 0.4549 - val_accuracy: 0.8073 - val_loss: 0.4498
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7830 - loss: 0.4536 - val_accuracy: 0.8073 - val_loss: 0.4499
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7778 - loss: 0.4527 - val_accuracy: 0.8021 - val_loss: 0.4500
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7830 - loss: 0.4521 - val_accuracy: 0.8021 - val_loss: 0.4497
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7865 - loss: 0.4511 - val_accuracy: 0.7969 - val_loss: 0.4499
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4505 - val_accuracy: 0.7969 - val_loss: 0.4500
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7830 - loss: 0.4492 - val_accuracy: 0.7969 - val_loss: 0.4504
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7917 - loss: 0.4487 - val_accuracy: 0.8021 - val_loss: 0.4509
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7830 - loss: 0.4477 - val_accuracy: 0.8021 - val_loss: 0.4507
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4467 - val_accuracy: 0.8021 - val_loss: 0.4507
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7882 - loss: 0.4469 - val_accuracy: 0.8021 - val_loss: 0.4514
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7917 - loss: 0.4454 - val_accuracy: 0.8021 - val_loss: 0.4519
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4446 - val_accuracy: 0.8073 - val_loss: 0.4523
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7882 - loss: 0.4441 - val_accuracy: 0.8073 - val_loss: 0.4522
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4437 - val_accuracy: 0.8073 - val_loss: 0.4524
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - loss: 0.4427 - val_accuracy: 0.8073 - val_loss: 0.4522
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7865 - loss: 0.4417 - val_accuracy: 0.8073 - val_loss: 0.4522
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7934 - loss: 0.4415 - val_accuracy: 0.8073 - val_loss: 0.4527
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4406 - val_accuracy: 0.8021 - val_loss: 0.4533
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7986 - loss: 0.4402 - val_accuracy: 0.8021 - val_loss: 0.4535
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8003 - loss: 0.4396 - val_accuracy: 0.8021 - val_loss: 0.4542
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7934 - loss: 0.4389 - val_accuracy: 0.8021 - val_loss: 0.4548
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7986 - loss: 0.4382 - val_accuracy: 0.8021 - val_loss: 0.4554
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7969 - loss: 0.4378 - val_accuracy: 0.8021 - val_loss: 0.4556
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7986 - loss: 0.4374 - val_accuracy: 0.8021 - val_loss: 0.4558
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4364 - val_accuracy: 0.8021 - val_loss: 0.4557
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4362 - val_accuracy: 0.8021 - val_loss: 0.4559
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4355 - val_accuracy: 0.8021 - val_loss: 0.4562
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8056 - loss: 0.4350 - val_accuracy: 0.8021 - val_loss: 0.4565
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4345 - val_accuracy: 0.8021 - val_loss: 0.4562
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4338 - val_accuracy: 0.7969 - val_loss: 0.4558
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4334 - val_accuracy: 0.7969 - val_loss: 0.4562
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7969 - loss: 0.4327 - val_accuracy: 0.7969 - val_loss: 0.4575
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4326 - val_accuracy: 0.7969 - val_loss: 0.4574
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4318 - val_accuracy: 0.7917 - val_loss: 0.4579
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4312 - val_accuracy: 0.7917 - val_loss: 0.4582
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4311 - val_accuracy: 0.7917 - val_loss: 0.4584
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8038 - loss: 0.4302 - val_accuracy: 0.7917 - val_loss: 0.4584
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4302 - val_accuracy: 0.7917 - val_loss: 0.4592
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4290 - val_accuracy: 0.7969 - val_loss: 0.4600
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4286 - val_accuracy: 0.7917 - val_loss: 0.4598
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4284 - val_accuracy: 0.7969 - val_loss: 0.4603
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4276 - val_accuracy: 0.7969 - val_loss: 0.4603
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4273 - val_accuracy: 0.7969 - val_loss: 0.4607
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4270 - val_accuracy: 0.7969 - val_loss: 0.4610
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4263 - val_accuracy: 0.7969 - val_loss: 0.4612
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4260 - val_accuracy: 0.7969 - val_loss: 0.4623
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7986 - loss: 0.4258 - val_accuracy: 0.7969 - val_loss: 0.4623
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4252 - val_accuracy: 0.7969 - val_loss: 0.4626
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4248 - val_accuracy: 0.7969 - val_loss: 0.4628
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4240 - val_accuracy: 0.7917 - val_loss: 0.4641
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.4237 - val_accuracy: 0.7969 - val_loss: 0.4641
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4233 - val_accuracy: 0.7969 - val_loss: 0.4646
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4231 - val_accuracy: 0.7969 - val_loss: 0.4649
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8090 - loss: 0.4219 - val_accuracy: 0.7917 - val_loss: 0.4653
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.4220 - val_accuracy: 0.7865 - val_loss: 0.4651
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4211 - val_accuracy: 0.7917 - val_loss: 0.4665
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4209 - val_accuracy: 0.7865 - val_loss: 0.4660
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4204 - val_accuracy: 0.7865 - val_loss: 0.4657
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.4200 - val_accuracy: 0.7865 - val_loss: 0.4657
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4197 - val_accuracy: 0.7865 - val_loss: 0.4661
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4193 - val_accuracy: 0.7865 - val_loss: 0.4663
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8090 - loss: 0.4188 - val_accuracy: 0.7865 - val_loss: 0.4668
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4183 - val_accuracy: 0.7865 - val_loss: 0.4668
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4177 - val_accuracy: 0.7865 - val_loss: 0.4667
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4174 - val_accuracy: 0.7865 - val_loss: 0.4682
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4170 - val_accuracy: 0.7865 - val_loss: 0.4685
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8090 - loss: 0.4166 - val_accuracy: 0.7865 - val_loss: 0.4684
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8056 - loss: 0.4163 - val_accuracy: 0.7865 - val_loss: 0.4682
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8056 - loss: 0.4158 - val_accuracy: 0.7865 - val_loss: 0.4682
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4160 - val_accuracy: 0.7865 - val_loss: 0.4686
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.4150 - val_accuracy: 0.7865 - val_loss: 0.4687
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.4152 - val_accuracy: 0.7917 - val_loss: 0.4696
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.4146 - val_accuracy: 0.7917 - val_loss: 0.4701

## No.of Nodes in a layer

In [34]:
def build_model(hp):
  model = Sequential()
  unit = hp.Int('unit',min_value = 8,max_value = 128,step = 8)
  model.add(Dense(units = unit,activation = 'relu',input_dim = 8))
  model.add(Dense(1,activation = 'sigmoid'))
  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics = ['accuracy'])
  return model

In [37]:
tuner = kt.RandomSearch(build_model,objective = "val_accuracy",max_trials= 5,directory = 'mydir')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7604166865348816

Best val_accuracy So Far: 0.7916666865348816
Total elapsed time: 00h 00m 14s

In [39]:
tuner.get_best_hyperparameters()[0].values

{'unit': 128}

In [48]:
model = tuner.get_best_models(num_models = 1)[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,281 (5.00 KB)

 Trainable params: 1,281 (5.00 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.fit(X_train,y_train,epochs = 100,initial_epoch = 5,validation_data = (X_test,y_test),batch_size = 32)

Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7726 - loss: 0.4843 - val_accuracy: 0.7917 - val_loss: 0.4554
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4745 - val_accuracy: 0.7917 - val_loss: 0.4488
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7778 - loss: 0.4689 - val_accuracy: 0.8073 - val_loss: 0.4460
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7760 - loss: 0.4643 - val_accuracy: 0.8021 - val_loss: 0.4428
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7778 - loss: 0.4609 - val_accuracy: 0.7969 - val_loss: 0.4423
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7795 - loss: 0.4582 - val_accuracy: 0.8021 - val_loss: 0.4432
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7812 - loss: 0.4556 - val_accuracy: 0.8021 - val_loss: 0.4412
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7795 - loss: 0.4530 - val_accuracy: 0.8073 - val_loss: 0.4411
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7778 - loss: 0.4509 - val_accuracy: 0.8021 - val_loss: 0.4413
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7830 - loss: 0.4482 - val_accuracy: 0.8021 - val_loss: 0.4414
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7882 - loss: 0.4468 - val_accuracy: 0.8021 - val_loss: 0.4423
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7847 - loss: 0.4446 - val_accuracy: 0.8021 - val_loss: 0.4426
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4426 - val_accuracy: 0.8021 - val_loss: 0.4438
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4403 - val_accuracy: 0.7917 - val_loss: 0.4445
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7830 - loss: 0.4391 - val_accuracy: 0.7969 - val_loss: 0.4442
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4376 - val_accuracy: 0.7917 - val_loss: 0.4455
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4356 - val_accuracy: 0.7917 - val_loss: 0.4478
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7951 - loss: 0.4341 - val_accuracy: 0.7969 - val_loss: 0.4484
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4330 - val_accuracy: 0.7969 - val_loss: 0.4485
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4317 - val_accuracy: 0.8021 - val_loss: 0.4482
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4295 - val_accuracy: 0.7969 - val_loss: 0.4520
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4284 - val_accuracy: 0.7917 - val_loss: 0.4517
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8038 - loss: 0.4269 - val_accuracy: 0.8021 - val_loss: 0.4525
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4259 - val_accuracy: 0.8021 - val_loss: 0.4524
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8021 - loss: 0.4249 - val_accuracy: 0.7969 - val_loss: 0.4542
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.4236 - val_accuracy: 0.8073 - val_loss: 0.4532
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8056 - loss: 0.4224 - val_accuracy: 0.7917 - val_loss: 0.4563
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4218 - val_accuracy: 0.8021 - val_loss: 0.4570
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8021 - loss: 0.4201 - val_accuracy: 0.7969 - val_loss: 0.4578
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8056 - loss: 0.4192 - val_accuracy: 0.8021 - val_loss: 0.4574
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8038 - loss: 0.4181 - val_accuracy: 0.8073 - val_loss: 0.4592
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8073 - loss: 0.4171 - val_accuracy: 0.7917 - val_loss: 0.4601
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8125 - loss: 0.4161 - val_accuracy: 0.7969 - val_loss: 0.4600
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8108 - loss: 0.4151 - val_accuracy: 0.7969 - val_loss: 0.4615
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8073 - loss: 0.4136 - val_accuracy: 0.8021 - val_loss: 0.4589
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8090 - loss: 0.4140 - val_accuracy: 0.7969 - val_loss: 0.4631
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8108 - loss: 0.4118 - val_accuracy: 0.8073 - val_loss: 0.4606
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8108 - loss: 0.4115 - val_accuracy: 0.7969 - val_loss: 0.4636
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8108 - loss: 0.4111 - val_accuracy: 0.7969 - val_loss: 0.4648
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8108 - loss: 0.4091 - val_accuracy: 0.8021 - val_loss: 0.4649
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8212 - loss: 0.4086 - val_accuracy: 0.8125 - val_loss: 0.4647
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8108 - loss: 0.4082 - val_accuracy: 0.8073 - val_loss: 0.4678
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4076 - val_accuracy: 0.7969 - val_loss: 0.4679
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8177 - loss: 0.4068 - val_accuracy: 0.7969 - val_loss: 0.4683
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4059 - val_accuracy: 0.8125 - val_loss: 0.4677
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8194 - loss: 0.4048 - val_accuracy: 0.8073 - val_loss: 0.4686
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8194 - loss: 0.4046 - val_accuracy: 0.8073 - val_loss: 0.4702
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8142 - loss: 0.4033 - val_accuracy: 0.8073 - val_loss: 0.4716
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4033 - val_accuracy: 0.8125 - val_loss: 0.4693
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4025 - val_accuracy: 0.8125 - val_loss: 0.4693
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.4016 - val_accuracy: 0.8073 - val_loss: 0.4692
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.4012 - val_accuracy: 0.8073 - val_loss: 0.4700
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.4003 - val_accuracy: 0.8073 - val_loss: 0.4689
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3995 - val_accuracy: 0.8125 - val_loss: 0.4681
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3989 - val_accuracy: 0.8073 - val_loss: 0.4704
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.3986 - val_accuracy: 0.8073 - val_loss: 0.4716
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8212 - loss: 0.3977 - val_accuracy: 0.8073 - val_loss: 0.4730
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.3970 - val_accuracy: 0.8073 - val_loss: 0.4711
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8177 - loss: 0.3972 - val_accuracy: 0.8125 - val_loss: 0.4706
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3963 - val_accuracy: 0.8125 - val_loss: 0.4727
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3953 - val_accuracy: 0.8073 - val_loss: 0.4729
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3947 - val_accuracy: 0.8073 - val_loss: 0.4718
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3948 - val_accuracy: 0.8073 - val_loss: 0.4744
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3931 - val_accuracy: 0.8073 - val_loss: 0.4748
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3928 - val_accuracy: 0.8125 - val_loss: 0.4740
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.3932 - val_accuracy: 0.8073 - val_loss: 0.4744
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.3914 - val_accuracy: 0.8021 - val_loss: 0.4767
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3911 - val_accuracy: 0.8021 - val_loss: 0.4790
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3905 - val_accuracy: 0.8021 - val_loss: 0.4769
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3902 - val_accuracy: 0.8021 - val_loss: 0.4793
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.3893 - val_accuracy: 0.8021 - val_loss: 0.4799
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.3886 - val_accuracy: 0.8073 - val_loss: 0.4793
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.3882 - val_accuracy: 0.8073 - val_loss: 0.4795
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3876 - val_accuracy: 0.7969 - val_loss: 0.4828
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3856 - val_accuracy: 0.8021 - val_loss: 0.4775
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3869 - val_accuracy: 0.8021 - val_loss: 0.4813
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3863 - val_accuracy: 0.8021 - val_loss: 0.4816
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3853 - val_accuracy: 0.8021 - val_loss: 0.4855
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8247 - loss: 0.3847 - val_accuracy: 0.8021 - val_loss: 0.4812
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3842 - val_accuracy: 0.8125 - val_loss: 0.4808
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3836 - val_accuracy: 0.8021 - val_loss: 0.4820
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3832 - val_accuracy: 0.7969 - val_loss: 0.4839
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3826 - val_accuracy: 0.8073 - val_loss: 0.4817
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3821 - val_accuracy: 0.8073 - val_loss: 0.4822
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3813 - val_accuracy: 0.8073 - val_loss: 0.4813
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8299 - loss: 0.3798 - val_accuracy: 0.8021 - val_loss: 0.4821
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3805 - val_accuracy: 0.7969 - val_loss: 0.4852
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3799 - val_accuracy: 0.7969 - val_loss: 0.4841
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3794 - val_accuracy: 0.7969 - val_loss: 0.4874
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.3785 - val_accuracy: 0.8073 - val_loss: 0.4860
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8281 - loss: 0.3793 - val_accuracy: 0.8021 - val_loss: 0.4858
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3779 - val_accuracy: 0.8021 - val_loss: 0.4872
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8264 - loss: 0.3773 - val_accuracy: 0.7969 - val_loss: 0.4884
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.3761 - val_accuracy: 0.7917 - val_loss: 0.4924
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3770 - val_accuracy: 0.7969 - val_loss: 0.4886

## How to select no.of layers

In [49]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(72,activation = 'relu',input_dim = 8))
  for i in range(hp.Int('num_layers',min_value = 1,max_value = 10)):
    model.add(Dense(72,activation = 'relu'))
  model.add(Dense(1,activation = 'sigmoid'))
  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics = ['accuracy'])
  return model

In [51]:
tuner = kt.RandomSearch(build_model,objective = 'val_accuracy',max_trials = 5,directory = 'mydirLayers',project_name = 'NumLayers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [52]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.8177083134651184

Best val_accuracy So Far: 0.8177083134651184
Total elapsed time: 00h 00m 24s

In [58]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3}

In [59]:
model = tuner.get_best_models(num_models = 1)[0]
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 72)             │           648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 72)             │         5,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            73 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16,489 (64.41 KB)

 Trainable params: 16,489 (64.41 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.fit(X_train,y_train,epochs = 100,initial_epoch = 5,validation_data = (X_test,y_test),batch_size = 32)

Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.7899 - loss: 0.4451 - val_accuracy: 0.8073 - val_loss: 0.4493
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4245 - val_accuracy: 0.8229 - val_loss: 0.4502
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4110 - val_accuracy: 0.7865 - val_loss: 0.4658
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8021 - loss: 0.4134 - val_accuracy: 0.7604 - val_loss: 0.4753
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3943 - val_accuracy: 0.7865 - val_loss: 0.4765
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8177 - loss: 0.3953 - val_accuracy: 0.7552 - val_loss: 0.4805
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8125 - loss: 0.3853 - val_accuracy: 0.7969 - val_loss: 0.4854
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3756 - val_accuracy: 0.7969 - val_loss: 0.4810
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3700 - val_accuracy: 0.7917 - val_loss: 0.4872
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8507 - loss: 0.3577 - val_accuracy: 0.7604 - val_loss: 0.4881
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.3551 - val_accuracy: 0.7708 - val_loss: 0.5012
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8542 - loss: 0.3436 - val_accuracy: 0.7448 - val_loss: 0.5072
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3386 - val_accuracy: 0.7865 - val_loss: 0.5117
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8715 - loss: 0.3152 - val_accuracy: 0.7656 - val_loss: 0.5592
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8715 - loss: 0.3221 - val_accuracy: 0.7396 - val_loss: 0.5151
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.3114 - val_accuracy: 0.7552 - val_loss: 0.5616
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8785 - loss: 0.3015 - val_accuracy: 0.7448 - val_loss: 0.5461
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8611 - loss: 0.3092 - val_accuracy: 0.7552 - val_loss: 0.5602
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2869 - val_accuracy: 0.7552 - val_loss: 0.5831
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2747 - val_accuracy: 0.7448 - val_loss: 0.5714
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8872 - loss: 0.2733 - val_accuracy: 0.7396 - val_loss: 0.5856
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9097 - loss: 0.2583 - val_accuracy: 0.7604 - val_loss: 0.5970
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2563 - val_accuracy: 0.7448 - val_loss: 0.6297
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9062 - loss: 0.2445 - val_accuracy: 0.7292 - val_loss: 0.5975
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9184 - loss: 0.2448 - val_accuracy: 0.7656 - val_loss: 0.6185
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9080 - loss: 0.2238 - val_accuracy: 0.7500 - val_loss: 0.6297
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9236 - loss: 0.2202 - val_accuracy: 0.7344 - val_loss: 0.7353
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9080 - loss: 0.2338 - val_accuracy: 0.7500 - val_loss: 0.7088
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9236 - loss: 0.2015 - val_accuracy: 0.7448 - val_loss: 0.7266
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9045 - loss: 0.2140 - val_accuracy: 0.7500 - val_loss: 0.6770
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9201 - loss: 0.1945 - val_accuracy: 0.7292 - val_loss: 0.7477
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9323 - loss: 0.1770 - val_accuracy: 0.7396 - val_loss: 0.7752
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9253 - loss: 0.1843 - val_accuracy: 0.7604 - val_loss: 0.7638
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9340 - loss: 0.1742 - val_accuracy: 0.7240 - val_loss: 0.7857
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9340 - loss: 0.1708 - val_accuracy: 0.7552 - val_loss: 0.8245
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9323 - loss: 0.1712 - val_accuracy: 0.7240 - val_loss: 0.8306
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9566 - loss: 0.1493 - val_accuracy: 0.7448 - val_loss: 0.8498
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9392 - loss: 0.1560 - val_accuracy: 0.7188 - val_loss: 0.9222
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9497 - loss: 0.1421 - val_accuracy: 0.7604 - val_loss: 0.8387
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9549 - loss: 0.1317 - val_accuracy: 0.7448 - val_loss: 0.8994
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9514 - loss: 0.1376 - val_accuracy: 0.7656 - val_loss: 0.9125
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9653 - loss: 0.1210 - val_accuracy: 0.7292 - val_loss: 0.9495
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9635 - loss: 0.1168 - val_accuracy: 0.7292 - val_loss: 0.9464
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9566 - loss: 0.1167 - val_accuracy: 0.7188 - val_loss: 0.9586
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9653 - loss: 0.1048 - val_accuracy: 0.7135 - val_loss: 0.9580
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9722 - loss: 0.0919 - val_accuracy: 0.7448 - val_loss: 0.9950
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.1033 - val_accuracy: 0.7292 - val_loss: 1.0332
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9705 - loss: 0.0898 - val_accuracy: 0.7344 - val_loss: 1.0309
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9514 - loss: 0.1107 - val_accuracy: 0.7396 - val_loss: 1.0533
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9740 - loss: 0.0803 - val_accuracy: 0.7344 - val_loss: 1.0463
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9601 - loss: 0.1000 - val_accuracy: 0.7292 - val_loss: 1.1409
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9826 - loss: 0.0703 - val_accuracy: 0.7500 - val_loss: 1.1306
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9618 - loss: 0.0862 - val_accuracy: 0.7292 - val_loss: 1.1385
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9844 - loss: 0.0719 - val_accuracy: 0.7396 - val_loss: 1.2165
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9722 - loss: 0.0755 - val_accuracy: 0.7292 - val_loss: 1.1724
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0470 - val_accuracy: 0.7344 - val_loss: 1.3578
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9670 - loss: 0.0727 - val_accuracy: 0.7656 - val_loss: 1.1971
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0440 - val_accuracy: 0.7292 - val_loss: 1.2807
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9740 - loss: 0.0673 - val_accuracy: 0.7188 - val_loss: 1.3120
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0387 - val_accuracy: 0.7396 - val_loss: 1.3529
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9722 - loss: 0.0797 - val_accuracy: 0.7552 - val_loss: 1.3101
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9826 - loss: 0.0508 - val_accuracy: 0.6875 - val_loss: 1.6061
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9878 - loss: 0.0503 - val_accuracy: 0.7344 - val_loss: 1.3565
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9931 - loss: 0.0344 - val_accuracy: 0.7448 - val_loss: 1.3626
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9826 - loss: 0.0614 - val_accuracy: 0.7292 - val_loss: 1.8371
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9809 - loss: 0.0665 - val_accuracy: 0.7292 - val_loss: 1.4728
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0348 - val_accuracy: 0.7344 - val_loss: 1.7695
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9896 - loss: 0.0441 - val_accuracy: 0.7292 - val_loss: 1.5134
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9878 - loss: 0.0392 - val_accuracy: 0.7448 - val_loss: 1.6593
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9774 - loss: 0.0623 - val_accuracy: 0.7760 - val_loss: 1.5729
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9983 - loss: 0.0179 - val_accuracy: 0.7396 - val_loss: 1.6582
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0371 - val_accuracy: 0.7396 - val_loss: 1.6040
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9983 - loss: 0.0145 - val_accuracy: 0.7240 - val_loss: 1.5996
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0402 - val_accuracy: 0.7135 - val_loss: 1.6376
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9809 - loss: 0.0413 - val_accuracy: 0.7344 - val_loss: 1.6450
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0118 - val_accuracy: 0.7083 - val_loss: 1.7321
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9878 - loss: 0.0475 - val_accuracy: 0.6927 - val_loss: 1.7475
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9809 - loss: 0.0554 - val_accuracy: 0.7135 - val_loss: 1.8454
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9931 - loss: 0.0220 - val_accuracy: 0.7344 - val_loss: 1.8223
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9983 - loss: 0.0137 - val_accuracy: 0.7292 - val_loss: 1.9507
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9705 - loss: 0.0811 - val_accuracy: 0.7240 - val_loss: 1.7869
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9983 - loss: 0.0103 - val_accuracy: 0.7552 - val_loss: 1.7619
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9965 - loss: 0.0122 - val_accuracy: 0.7292 - val_loss: 1.9066
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0073 - val_accuracy: 0.7552 - val_loss: 1.9347
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9861 - loss: 0.0512 - val_accuracy: 0.7552 - val_loss: 1.9377
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9913 - loss: 0.0200 - val_accuracy: 0.7135 - val_loss: 2.0840
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9948 - loss: 0.0227 - val_accuracy: 0.7344 - val_loss: 1.9812
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.7344 - val_loss: 2.0286
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9913 - loss: 0.0171 - val_accuracy: 0.7396 - val_loss: 2.4643
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9844 - loss: 0.0472 - val_accuracy: 0.7083 - val_loss: 2.0497
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0208 - val_accuracy: 0.7344 - val_loss: 1.9815
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0052 - val_accuracy: 0.7292 - val_loss: 1.9811
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9896 - loss: 0.0286 - val_accuracy: 0.7240 - val_loss: 2.0655
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9965 - loss: 0.0108 - val_accuracy: 0.7240 - val_loss: 2.0945
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9948 - loss: 0.0140 - val_accuracy: 0.7292 - val_loss: 2.1995

## All in ALL one model

In [78]:
def build_model(hp):
  model = Sequential()
  counter = 0;
  for i in range(hp.Int('num_layers',min_value = 1,max_value = 10)):
    if ( counter == 0) :
      model.add(
        Dense(
            units=hp.Int('units' + str(i),
            min_value = 8,
            max_value = 128,
            step = 8),
            activation = hp.Choice('activation' + str(i),values = ['relu','tanh','sigmoid']),
            input_dim = 8
        )
      )
      model.add(Dropout(hp.Choice('dropout' + str(i),values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
              units=hp.Int('units' + str(i),
              min_value = 8,
              max_value = 128,
              step = 8),
              activation = hp.Choice('activation' + str(i),values = ['relu','tanh','sigmoid'])
          )
      )
      model.add(Dropout(hp.Choice('dropout' + str(i),values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter = counter + 1
  model.add(Dense(1,activation = 'sigmoid'))
  model.compile(optimizer = hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']),loss = 'binary_crossentropy',metrics = ['accuracy'])
  return model

In [79]:
tuner = kt.RandomSearch(
    build_model,
    objective = 'val_accuracy',
    max_trials = 5,
    directory = 'mydirAll',
    project_name = 'All'
)

Reloading Tuner from mydirAll/All/tuner0.json

In [80]:
tuner.search(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

In [81]:
model = tuner.get_best_models(num_models = 1)[0]
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 104)            │           936 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 104)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         3,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           264 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,713 (18.41 KB)

 Trainable params: 4,713 (18.41 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
model.fit(X_train,y_train,epochs = 100,initial_epoch = 5,validation_data = (X_test,y_test),batch_size = 32)

Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.7118 - loss: 0.5340 - val_accuracy: 0.7917 - val_loss: 0.4598
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6997 - loss: 0.5229 - val_accuracy: 0.8177 - val_loss: 0.4587
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7448 - loss: 0.5367 - val_accuracy: 0.8073 - val_loss: 0.4584
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7361 - loss: 0.5256 - val_accuracy: 0.8177 - val_loss: 0.4570
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7639 - loss: 0.5115 - val_accuracy: 0.8073 - val_loss: 0.4536
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.5153 - val_accuracy: 0.8073 - val_loss: 0.4576
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4964 - val_accuracy: 0.8073 - val_loss: 0.4544
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7587 - loss: 0.5013 - val_accuracy: 0.8125 - val_loss: 0.4522
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7604 - loss: 0.4845 - val_accuracy: 0.7969 - val_loss: 0.4584
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7674 - loss: 0.4778 - val_accuracy: 0.7969 - val_loss: 0.4495
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7639 - loss: 0.4945 - val_accuracy: 0.7969 - val_loss: 0.4541
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7917 - loss: 0.4773 - val_accuracy: 0.8021 - val_loss: 0.4562
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7691 - loss: 0.4763 - val_accuracy: 0.8073 - val_loss: 0.4528
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7691 - loss: 0.4670 - val_accuracy: 0.8021 - val_loss: 0.4616
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4685 - val_accuracy: 0.7969 - val_loss: 0.4553
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.4892 - val_accuracy: 0.8125 - val_loss: 0.4611
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7812 - loss: 0.4614 - val_accuracy: 0.8021 - val_loss: 0.4548
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7795 - loss: 0.4600 - val_accuracy: 0.8021 - val_loss: 0.4568
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7778 - loss: 0.4483 - val_accuracy: 0.8021 - val_loss: 0.4624
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7865 - loss: 0.4559 - val_accuracy: 0.8073 - val_loss: 0.4667
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7743 - loss: 0.4634 - val_accuracy: 0.8073 - val_loss: 0.4592
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7917 - loss: 0.4393 - val_accuracy: 0.7969 - val_loss: 0.4641
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7812 - loss: 0.4472 - val_accuracy: 0.7917 - val_loss: 0.4664
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8003 - loss: 0.4492 - val_accuracy: 0.7969 - val_loss: 0.4609
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8003 - loss: 0.4345 - val_accuracy: 0.7812 - val_loss: 0.4746
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7934 - loss: 0.4240 - val_accuracy: 0.7865 - val_loss: 0.4729
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7969 - loss: 0.4420 - val_accuracy: 0.7969 - val_loss: 0.4752
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8038 - loss: 0.4417 - val_accuracy: 0.7865 - val_loss: 0.4742
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7969 - loss: 0.4315 - val_accuracy: 0.7969 - val_loss: 0.4766
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7969 - loss: 0.4269 - val_accuracy: 0.7969 - val_loss: 0.4789
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8125 - loss: 0.4291 - val_accuracy: 0.8073 - val_loss: 0.4776
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8056 - loss: 0.4347 - val_accuracy: 0.7917 - val_loss: 0.4855
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.4443 - val_accuracy: 0.7865 - val_loss: 0.4764
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8142 - loss: 0.4212 - val_accuracy: 0.7760 - val_loss: 0.4790
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8229 - loss: 0.4334 - val_accuracy: 0.7812 - val_loss: 0.4825
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8073 - loss: 0.4031 - val_accuracy: 0.7656 - val_loss: 0.4926
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8212 - loss: 0.4178 - val_accuracy: 0.7708 - val_loss: 0.4998
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8247 - loss: 0.4089 - val_accuracy: 0.7760 - val_loss: 0.5026
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8212 - loss: 0.3941 - val_accuracy: 0.7760 - val_loss: 0.5034
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8090 - loss: 0.4171 - val_accuracy: 0.7552 - val_loss: 0.5075
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8281 - loss: 0.4012 - val_accuracy: 0.7760 - val_loss: 0.4956
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8299 - loss: 0.4041 - val_accuracy: 0.7708 - val_loss: 0.4992
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8229 - loss: 0.3884 - val_accuracy: 0.7760 - val_loss: 0.4996
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8403 - loss: 0.3705 - val_accuracy: 0.7760 - val_loss: 0.5111
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.3754 - val_accuracy: 0.7656 - val_loss: 0.5085
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8316 - loss: 0.3997 - val_accuracy: 0.7552 - val_loss: 0.5085
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.3860 - val_accuracy: 0.7656 - val_loss: 0.5308
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8351 - loss: 0.3826 - val_accuracy: 0.7552 - val_loss: 0.5317
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8333 - loss: 0.3843 - val_accuracy: 0.7656 - val_loss: 0.5260
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8385 - loss: 0.3795 - val_accuracy: 0.7708 - val_loss: 0.5107
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8490 - loss: 0.3688 - val_accuracy: 0.7500 - val_loss: 0.5197
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8403 - loss: 0.3578 - val_accuracy: 0.7656 - val_loss: 0.5244
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8438 - loss: 0.3460 - val_accuracy: 0.7552 - val_loss: 0.5409
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8455 - loss: 0.3667 - val_accuracy: 0.7708 - val_loss: 0.5336
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8472 - loss: 0.3464 - val_accuracy: 0.7604 - val_loss: 0.5353
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8385 - loss: 0.3857 - val_accuracy: 0.7396 - val_loss: 0.5287
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.3462 - val_accuracy: 0.7760 - val_loss: 0.5180
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.3798 - val_accuracy: 0.7604 - val_loss: 0.5498
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8455 - loss: 0.3590 - val_accuracy: 0.7500 - val_loss: 0.5502
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8611 - loss: 0.3342 - val_accuracy: 0.7604 - val_loss: 0.5340
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8507 - loss: 0.3337 - val_accuracy: 0.7500 - val_loss: 0.5478
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8455 - loss: 0.3601 - val_accuracy: 0.7448 - val_loss: 0.5648
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8472 - loss: 0.3450 - val_accuracy: 0.7448 - val_loss: 0.5500
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8802 - loss: 0.3196 - val_accuracy: 0.7448 - val_loss: 0.5566
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8507 - loss: 0.3413 - val_accuracy: 0.7500 - val_loss: 0.5632
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8611 - loss: 0.3414 - val_accuracy: 0.7500 - val_loss: 0.5801
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8611 - loss: 0.3464 - val_accuracy: 0.7292 - val_loss: 0.5757
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3106 - val_accuracy: 0.7500 - val_loss: 0.5643
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8733 - loss: 0.3274 - val_accuracy: 0.7500 - val_loss: 0.5755
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8715 - loss: 0.3041 - val_accuracy: 0.7344 - val_loss: 0.5924
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8646 - loss: 0.3154 - val_accuracy: 0.7344 - val_loss: 0.5982
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8628 - loss: 0.3260 - val_accuracy: 0.7448 - val_loss: 0.6062
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8698 - loss: 0.3253 - val_accuracy: 0.7396 - val_loss: 0.6036
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8524 - loss: 0.3497 - val_accuracy: 0.7344 - val_loss: 0.5853
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8611 - loss: 0.3170 - val_accuracy: 0.7396 - val_loss: 0.5784
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3063 - val_accuracy: 0.7448 - val_loss: 0.5989
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3121 - val_accuracy: 0.7708 - val_loss: 0.5903
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8542 - loss: 0.3404 - val_accuracy: 0.7396 - val_loss: 0.5883
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8733 - loss: 0.3098 - val_accuracy: 0.7344 - val_loss: 0.6027
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8819 - loss: 0.3082 - val_accuracy: 0.7292 - val_loss: 0.6159
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8837 - loss: 0.2925 - val_accuracy: 0.7344 - val_loss: 0.5990
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8767 - loss: 0.3096 - val_accuracy: 0.7500 - val_loss: 0.5914
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3271 - val_accuracy: 0.7760 - val_loss: 0.5914
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8715 - loss: 0.3091 - val_accuracy: 0.7500 - val_loss: 0.5832
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8889 - loss: 0.2825 - val_accuracy: 0.7812 - val_loss: 0.5955
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8681 - loss: 0.3079 - val_accuracy: 0.7865 - val_loss: 0.6062
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8767 - loss: 0.3074 - val_accuracy: 0.7500 - val_loss: 0.6119
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8837 - loss: 0.3023 - val_accuracy: 0.7396 - val_loss: 0.5988
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8750 - loss: 0.2813 - val_accuracy: 0.7604 - val_loss: 0.5992
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8715 - loss: 0.2914 - val_accuracy: 0.7604 - val_loss: 0.5920
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8750 - loss: 0.3066 - val_accuracy: 0.7396 - val_loss: 0.5970
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8941 - loss: 0.2924 - val_accuracy: 0.7604 - val_loss: 0.5921
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8646 - loss: 0.3123 - val_accuracy: 0.7448 - val_loss: 0.5919
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8924 - loss: 0.2948 - val_accuracy: 0.7448 - val_loss: 0.6004
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8941 - loss: 0.2788 - val_accuracy: 0.7552 - val_loss: 0.6318